### ISSUE TITLE
Toegang tot wiki

### ISSUE THREAD

**Issue by brussee** [csrdelft/wiki#2]
Ik hoop dat iedereen door heeft dat de komma een **OR** is: `P_LOGGED_IN,groep:wikitoegang` in https://github.com/brussee/wiki/blob/f07fa7c2d61445d7f0e168760d455d9e0f739482/lib/plugins/authcsr/auth.php#L91

**Comment by qurben** [comment]
Ja, die comment is niet helemaal op z'n plek.

Er zijn gebruikers zonder P_LOGGED_IN die wel op de wiki mogen. Op dit moment is dat helaas een beetje brak, omdat deze accounts geen wachtwoord kunnen aanvragen.
